import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Header1 from "./common/Header1";
import Footer from "./common/Footer";
import Mainlayout from "./Mainlayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Mainlayout>
       <html lang="en">
      <body className={inter.className}>
        <Header1/>
        <Header/>
     
        
        {children}
        <Footer/>
        </body>
    </html>
    </Mainlayout>

   
  );
}
